# This will exclude phase protection from certain blocks.
excluded_blocks:
  - "SLIME_BLOCK"
  - "CAULDRON"
  - "BREWING_STAND"
  - "PISTON_MOVING_PIECE"
  - "PISTON_STICKY_BASE"
  - "PISTON_BASE"
  - "HOPPER"
  - "COBBLESTONE_STAIRS"
  - "OAK_STAIRS"
  - "BRICK_STAIRS"
  - "STONE_BRICK_STAIRS"
  - "NETHER_BRICK_STAIRS"
  - "SANDSTONE_STAIRS"
  - "SPRUCE_STAIRS"
  - "BIRCH_STAIRS"
  - "JUNGLE_STAIRS"
  - "QUARTZ_STAIRS"
  - "ACACIA_STAIRS"
  - "DARK_OAK_STAIRS"
  - "RED_SANDSTONE_STAIRS"
# The message sent to players with Phase alerts on.
alert_message: "&8[&4!&8] &c%player% &7was caught phasing/vclipping."
# The max movement before a the move packet is cancelled (recommended to leave alone).
max_move: 10
enderpearl_stuck_protection: true