# This will exclude phase protection from certain blocks.
excluded_blocks:
  - "SLIME_BLOCK"
  - "CAULDRON"
  - "BREWING_STAND"
  - "PISTON_MOVING_PIECE"
  - "PISTON_STICKY_BASE"
  - "PISTON_BASE"
  - "SOUL_SAND"
# The message sent to players with Phase alerts on.
alert_message: "&8[&4!&8] &c%player% &7was caught phasing/vclipping. &8[&c%block%&8]"
# The max movement before a the move packet is cancelled (recommended to leave alone).
max_move: 10